### ISSUE TITLE
Horizontal list should not have space from sides

### ISSUE THREAD

**Issue by mashish584** [soorajck/uiNativeDummy#10]
While scrolling the horizontal list there shouldn't be any space from both sides. Initially there will be margin left for first item as per screen spacing from left side but it will be scrollable throughout the screen.
![Simulator Screen Shot - iPhone 12 mini - 2022-01-20 at 09 43 22](https://user-images.githubusercontent.com/33250693/150272262-471c288b-4ccc-477f-a494-757f0689576a.png)

**Comment by soorajck** [comment]
@mashish584 this issue is resolved and merged to main branch
